version: '3'

services:
  supply-side:
    build:
      context: .
      dockerfile: Dockerfile.supply
    ports:
      - 8000:8000
    depends_on:
      - db

  demand-side:
    build:
      context: .
      dockerfile: Dockerfile.demand
    ports:
      - 8001:8001
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auction_service
    ports:
      - 3306:3306
